"""
Flow-topology fork detector
===========================
Topology-based separatrix / attractor detection on an estimated drift
field, as a sibling to :mod:`scjdo.atlas.operator_metrics`.

Why this module exists
----------------------
``operator_metrics.max_unstable_eigenvalue`` reads instability off the
Jacobian spectrum at a single point in state space. That criterion
cannot distinguish a separatrix (a codimension-1 boundary between
basins) from a saddle that is not a fate decision — both produce a
positive real eigenvalue. On a bifurcating system, the spectral test
therefore conflates the two.

The flow-topology fix computes fate as a geometric property of the
integrated flow, not the local linearisation:

1. Deterministically integrate seeds forward under ``v(x)``; assign
   each seed to its terminal cluster (basin).
2. Compute the finite-time Lyapunov exponent (FTLE) — the maximum
   stretching rate of the flow map — on a neighbourhood of each seed.
   Ridges of the FTLE field are, by construction, the separatrices.

Both steps use the ``simulate.euler_integrate`` primitive that already
exists in the package; nothing new is required from the drift model.

Composition
-----------
``compute_ftle`` returns the raw FTLE field. ``assign_basins`` returns
the discrete basin label per seed. ``fork_detector`` combines them:
seeds with high FTLE that also sit between at least two distinct basin
labels among their nearest neighbours are flagged as fork points.
"""
from __future__ import annotations

from typing import Callable, Optional

import numpy as np
import torch

from scjdo.simulate.trajectories import euler_integrate


# ---------------------------------------------------------------------------
# FTLE via finite-difference flow-map Jacobian
# ---------------------------------------------------------------------------

def compute_ftle(
    drift_model,
    seeds: torch.Tensor,
    t0: float = 0.0,
    t1: float = 1.0,
    steps: int = 100,
    delta: float = 1e-3,
    device: Optional[str] = None,
) -> np.ndarray:
    """
    Finite-time Lyapunov exponent of the flow generated by ``drift_model``.

    For each seed ``x0``, the flow map Φ(x0; t0, t1) is estimated by
    forward Euler integration under the deterministic drift. The Jacobian
    ``F = ∂Φ/∂x`` is estimated by central finite differences with step
    ``delta`` along each state dimension. The FTLE is then

        σ(x0) = (1 / (t1 - t0)) * log(sqrt(λmax(FᵀF))),

    which measures how fast nearby trajectories separate over the window.
    Ridges of σ are Lagrangian coherent structures — separatrices in
    bistable / bifurcating systems.

    Parameters
    ----------
    drift_model : callable
        A ``(x, t) -> v`` model compatible with
        ``scjdo.simulate.euler_integrate``. Must be deterministic.
    seeds : Tensor, shape (N, D)
        Points at which to evaluate FTLE.
    t0, t1, steps : float, float, int
        Integration window and number of Euler steps.
    delta : float
        Finite-difference step for the flow-map Jacobian. Should be
        small relative to the scale of state-space variation but large
        enough to escape floating-point noise; 1e-3 in normalised
        coordinates is typical.
    device : str, optional
        Device for integration. Defaults to seeds.device.

    Returns
    -------
    np.ndarray, shape (N,)
        FTLE value per seed. Higher = more separation over the window.
        Ridges (local maxima in the direction normal to the ridge line)
        identify separatrices.
    """
    if device is None:
        device = str(seeds.device)
    seeds = seeds.to(device)
    N, D = seeds.shape
    duration = float(t1 - t0)
    if duration <= 0:
        raise ValueError("t1 must be strictly greater than t0")

    # Perturbations for each state dimension, both signs (central diff).
    eye = torch.eye(D, device=device, dtype=seeds.dtype) * delta
    # Stack: rows are [seed_i, seed_i + delta*e_j, seed_i - delta*e_j] for each j.
    plus = seeds[:, None, :] + eye[None, :, :]        # (N, D, D)
    minus = seeds[:, None, :] - eye[None, :, :]       # (N, D, D)

    batch = torch.cat(
        [
            seeds,
            plus.reshape(N * D, D),
            minus.reshape(N * D, D),
        ],
        dim=0,
    )
    traj = euler_integrate(
        drift_model, batch, t0=t0, t1=t1, steps=steps, stochastic=False
    )
    # traj has shape (B, steps, D); take terminal state.
    end = traj[:, -1, :]  # (B, D)

    end_seed = end[:N]                                     # (N, D)
    end_plus = end[N : N + N * D].reshape(N, D, D)         # (N, j, D)
    end_minus = end[N + N * D :].reshape(N, D, D)          # (N, j, D)

    # Flow-map Jacobian F[n, i, j] = ∂Φ_i(x_n)/∂x_j via central diff.
    # end_plus[n, j, i] - end_minus[n, j, i]  is  ΔΦ_i wrt component j.
    F = (end_plus - end_minus).transpose(1, 2) / (2.0 * delta)  # (N, D, D)

    # Cauchy-Green tensor and its top eigenvalue.
    CG = torch.matmul(F.transpose(1, 2), F)                     # (N, D, D)
    eigvals = torch.linalg.eigvalsh(CG)                         # (N, D), sorted asc
    lam_max = eigvals[:, -1].clamp_min(1e-30)
    ftle = (0.5 / duration) * torch.log(lam_max)
    return ftle.detach().cpu().numpy()


# ---------------------------------------------------------------------------
# Basin assignment via deterministic forward integration
# ---------------------------------------------------------------------------

def assign_basins(
    drift_model,
    seeds: torch.Tensor,
    t0: float = 0.0,
    t1: float = 1.0,
    steps: int = 200,
    cluster_fn: Optional[Callable[[np.ndarray], np.ndarray]] = None,
    n_attractors: int = 2,
    device: Optional[str] = None,
) -> tuple[np.ndarray, np.ndarray]:
    """
    Assign each seed to a basin of attraction via deterministic integration.

    Integrates seeds forward under the drift, clusters terminal states,
    and returns the basin label per seed. The separatrix is where
    infinitesimally close seeds land in different basins — so
    disagreement in basin labels among the k-nearest seeds is a
    geometric detector of the fate boundary.

    Parameters
    ----------
    drift_model : callable
        Deterministic ``(x, t) -> v`` model.
    seeds : Tensor, shape (N, D)
        Points to assign.
    t0, t1, steps : float, float, int
        Integration window; ``t1`` should be long enough that trajectories
        approach their attractors.
    cluster_fn : callable, optional
        Function mapping terminal-state array (N, D) → labels (N,). If
        omitted, k-means with ``n_attractors`` clusters is used.
    n_attractors : int
        Number of clusters for the default k-means.
    device : str, optional
        Device for integration.

    Returns
    -------
    labels : np.ndarray, shape (N,)
        Integer basin label per seed.
    terminal : np.ndarray, shape (N, D)
        Terminal state after integration (useful for diagnostics).
    """
    if device is None:
        device = str(seeds.device)
    seeds = seeds.to(device)

    traj = euler_integrate(
        drift_model, seeds, t0=t0, t1=t1, steps=steps, stochastic=False
    )
    terminal = traj[:, -1, :].detach().cpu().numpy()

    if cluster_fn is None:
        try:
            from sklearn.cluster import KMeans
        except ImportError as e:  # pragma: no cover - sklearn is a hard dep
            raise ImportError(
                "assign_basins default clusterer requires scikit-learn; "
                "pass cluster_fn to override."
            ) from e
        km = KMeans(n_clusters=n_attractors, n_init=10, random_state=0)
        labels = km.fit_predict(terminal).astype(np.int64)
    else:
        labels = np.asarray(cluster_fn(terminal), dtype=np.int64)

    return labels, terminal


# ---------------------------------------------------------------------------
# Fork detection: FTLE ridges consistent with basin disagreement
# ---------------------------------------------------------------------------

def fork_detector(
    drift_model,
    seeds: torch.Tensor,
    *,
    t0: float = 0.0,
    t1: float = 1.0,
    steps: int = 200,
    delta: float = 1e-3,
    n_attractors: int = 2,
    ftle_percentile: float = 90.0,
    k_neighbours: int = 10,
    device: Optional[str] = None,
) -> dict:
    """
    Combined topology-based fork detector.

    A seed is called a fork point when both:
      - its FTLE exceeds ``ftle_percentile`` of the population, AND
      - at least two distinct basin labels appear among its
        ``k_neighbours`` nearest seeds in state space.

    The FTLE test locates the separatrix ridge; the basin test confirms
    that the ridge actually separates fates (and is not just a
    fast-stretching region within a single basin). This is what a
    spectral ``Re(λmax) > τ`` criterion cannot do: a saddle that isn't
    on the boundary between basins passes the eigenvalue test but fails
    the basin-disagreement test, and is correctly excluded here.

    Returns
    -------
    dict with keys:
        ftle          : np.ndarray (N,)   FTLE per seed
        basins        : np.ndarray (N,)   basin label per seed
        terminal      : np.ndarray (N, D) terminal state per seed
        is_fork       : np.ndarray (N,) bool  final fork mask
        ftle_ridge    : np.ndarray (N,) bool  passed FTLE percentile test
        basin_boundary: np.ndarray (N,) bool  had disagreeing neighbours
        summary       : str
    """
    ftle = compute_ftle(
        drift_model, seeds, t0=t0, t1=t1, steps=steps, delta=delta, device=device
    )
    labels, terminal = assign_basins(
        drift_model, seeds, t0=t0, t1=t1, steps=steps,
        n_attractors=n_attractors, device=device,
    )

    ftle_thr = float(np.percentile(ftle, ftle_percentile))
    ftle_ridge = ftle >= ftle_thr

    try:
        from sklearn.neighbors import NearestNeighbors
    except ImportError as e:  # pragma: no cover
        raise ImportError(
            "fork_detector requires scikit-learn for neighbour lookup."
        ) from e

    X = seeds.detach().cpu().numpy()
    N = X.shape[0]
    k = min(k_neighbours + 1, N)
    nn = NearestNeighbors(n_neighbors=k).fit(X)
    _, idx = nn.kneighbors(X)
    neigh_labels = labels[idx[:, 1:]]  # drop self
    basin_boundary = np.array(
        [len(np.unique(row)) > 1 for row in neigh_labels], dtype=bool
    )

    is_fork = ftle_ridge & basin_boundary
    summary = (
        f"fork_detector: N={N} seeds, {n_attractors} attractors\n"
        f"  FTLE threshold (p{ftle_percentile:.0f}): {ftle_thr:.4f}\n"
        f"  ridge seeds: {int(ftle_ridge.sum())}\n"
        f"  basin-boundary seeds: {int(basin_boundary.sum())}\n"
        f"  confirmed forks (ridge ∧ boundary): {int(is_fork.sum())}"
    )
    return {
        "ftle": ftle,
        "basins": labels,
        "terminal": terminal,
        "is_fork": is_fork,
        "ftle_ridge": ftle_ridge,
        "basin_boundary": basin_boundary,
        "summary": summary,
    }
