"""
Top-HVG null for the Dynamo/SpliceJAC concordance analysis (critique v5 #4).

The published concordance uses an ANALYTIC null Jaccard for two random top-K
sets drawn from a size-V vocabulary: E[J] = K / (2V - K). In the shipped
notebook V = n_vars (total gene vocabulary), which is a permissive null
because scJDO and Dynamo both operate on the SAME top-HVG subset — they
literally cannot draw genes outside the HVG set. The correct null is
V = n_top_HVGs.

Reads observed Jaccard values from the CURRENT concordance pipeline output
at `analysis/figure4_concordance/concordance_metrics.json` (regenerated by
fig4_04_concordance_metrics.ipynb). No fallback: if the fresh file is missing,
run fig4_04 first — a stale snapshot would silently divorce the manuscript
numbers from the reproducible pipeline.

Also runs an empirical permutation null for cross-check.
"""
from __future__ import annotations

import json
from pathlib import Path

import numpy as np

REPO = Path("/Users/terooatt/Downloads/scJDO")
SRC = REPO / "analysis" / "figure4_concordance" / "concordance_metrics.json"
if not SRC.exists():
    raise FileNotFoundError(
        f"{SRC} missing — run analysis/figure4_concordance/fig4_04_concordance_metrics.ipynb "
        f"first to regenerate it."
    )
print(f"[top_hvg_null] reading Jaccard values from: {SRC.relative_to(REPO)}")
M = json.load(open(SRC))
_t3 = M["T3_transition_gene_lists"]
_dynamo = _t3["Dynamo"]
_splice = _t3["SpliceJAC"]
N_CELLS = M["n_cells"]
N_VARS = M["n_genes"]           # 6482 — total gene vocabulary
TOP_K = _dynamo["top_k"]  # 30

# HVG count: for scvelo.datasets.bonemarrow the shipped concordance pipeline
# uses n_top_genes=2000 (Scanpy Seurat flavor) — this is the vocabulary that
# scJDO and Dynamo actually draw their top-30 lists from.
N_TOP_HVGS = 2000

# --- analytic nulls
def analytic_null(K, V):
    return K / max(2 * V - K, 1)


null_random_gene = analytic_null(TOP_K, N_VARS)
null_top_hvg = analytic_null(TOP_K, N_TOP_HVGS)


def report(label, obs_mean_jacc):
    fold_rg = obs_mean_jacc / max(null_random_gene, 1e-12)
    fold_hvg = obs_mean_jacc / max(null_top_hvg, 1e-12)
    print(f"  {label}: mean Jaccard = {obs_mean_jacc:.4f}")
    print(f"    random-gene null (V={N_VARS}):  {null_random_gene:.5f}  →  "
          f"fold = {fold_rg:5.1f}×")
    print(f"    top-HVG null    (V={N_TOP_HVGS}):  {null_top_hvg:.5f}  →  "
          f"fold = {fold_hvg:5.1f}×")
    return fold_rg, fold_hvg


print(f"K = {TOP_K}  (top instability genes per cluster)")
print(f"N_cells = {N_CELLS}, N_vars = {N_VARS}, N_top_HVGs (assumed) = {N_TOP_HVGS}")
print()

# --- empirical permutation null: sample K genes uniformly at random from V,
# compute Jaccard against a fixed reference set of size K, repeat.
def empirical_null(K, V, n_trials=20000, seed=0):
    rng = np.random.default_rng(seed)
    ref = set(rng.choice(V, size=K, replace=False))
    js = np.empty(n_trials)
    for i in range(n_trials):
        smp = set(rng.choice(V, size=K, replace=False))
        js[i] = len(ref & smp) / len(ref | smp)
    return float(js.mean()), float(np.percentile(js, 95))


emp_rg_mean, emp_rg_95 = empirical_null(TOP_K, N_VARS)
emp_hvg_mean, emp_hvg_95 = empirical_null(TOP_K, N_TOP_HVGS)
print(f"Empirical (20k trials): random-gene mean {emp_rg_mean:.5f} (95th {emp_rg_95:.4f})")
print(f"Empirical (20k trials): top-HVG    mean {emp_hvg_mean:.5f} (95th {emp_hvg_95:.4f})")
print()

# --- report both concordance measurements
print("Concordance folds under both nulls:")
d_jacc = _dynamo["mean_jaccard"]
s_jacc = _splice["mean_jaccard"]
print()
d_fold_rg, d_fold_hvg = report("Dynamo",    d_jacc)
print()
s_fold_rg, s_fold_hvg = report("SpliceJAC", s_jacc)

print()
print("Manuscript-ready sentence:")
print(f"  Dynamo transition-gene overlap fold-over-null = {d_fold_rg:.0f}× against a")
print(f"  random-gene null (all {N_VARS} measured genes) and {d_fold_hvg:.0f}× against")
print(f"  a top-HVG null (V = {N_TOP_HVGS}, the vocabulary both methods draw from);")
print(f"  SpliceJAC fold-over-null = {s_fold_rg:.0f}× (random-gene) / {s_fold_hvg:.0f}× (top-HVG).")

# Save
out = {
    "params": {"top_K": TOP_K, "n_vars": N_VARS, "n_top_HVGs": N_TOP_HVGS},
    "analytic_nulls": {
        "random_gene": null_random_gene,
        "top_HVG": null_top_hvg,
    },
    "empirical_nulls": {
        "random_gene_mean": emp_rg_mean,
        "random_gene_95th": emp_rg_95,
        "top_HVG_mean": emp_hvg_mean,
        "top_HVG_95th": emp_hvg_95,
    },
    "Dynamo": {
        "mean_jaccard": d_jacc,
        "fold_over_random_gene_null": d_fold_rg,
        "fold_over_top_HVG_null": d_fold_hvg,
    },
    "SpliceJAC": {
        "mean_jaccard": s_jacc,
        "fold_over_random_gene_null": s_fold_rg,
        "fold_over_top_HVG_null": s_fold_hvg,
    },
}
Path("/Users/terooatt/Downloads/scJDO/scratchpad_run/top_hvg_null.json").write_text(
    json.dumps(out, indent=2)
)
print(f"\nSaved: /Users/terooatt/Downloads/scJDO/scratchpad_run/top_hvg_null.json")
